const express = require('express'); 
const cors = require('cors'); // Cross-Origin Resource Sharing
const path = require('path');
const { isValid, parseISO, format } = require('date-fns');
const fs = require('fs');

const db = require('./db'); // Imports db initialization
const dbHelper = require('./dbHelper');

require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

let statusOptions = [];

const app = express(); // Starts Express. 'app' is the main application object
const frontendUrl = process.env.FRONTEND_URL || 'http://localhost:3001';

app.use(cors({
  origin: frontendUrl
}));

app.use(express.json()); // Parses incoming JSON requests into JS objects (json --> js)

/**
 * Checks with a regex if a date string is valid.
 * @param {string} dateString - The date string in YYYY-MM-DD format.
 * @returns {boolean}
 */
const isValidDate = (dateString) => {
  if (!dateString) return true; // Null or empty date is acceptable

  const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  if (!dateRegex.test(dateString)) return false;

  const parsedDate = parseISO(dateString); // date-fns validation
  return isValid(parsedDate); 
};

/**
 * Returns the statusOptions from the Salesforce picklist field.
 */
app.get('/api/status-options', (req, res) => { 
  res.json(statusOptions);
});

/**
 * Get all employees.
 * Can include inactive employees or filter by a specific week.
 */
app.get('/api/employees', async (req, res) => { 
  // When a request hits this endpoint, execute this code
  // req includes everything the host sends: req.body, req.params (:), req.query (?)
  // res is the object you send back to the host: res.send, res.json, ...
  const includeInactive = req.query.includeInactive === 'true'; // If includeInactive was passed, the var becomes true
  const weekStart = req.query.weekStart; 
  const weekEnd = req.query.weekEnd;
  
  if (!isValidDate(weekStart) || !isValidDate(weekEnd)) {
    return res.status(400).json({ error: 'Invalid date.' }); // Date check
  }
  
  try {
    const rows = await dbHelper.getEmployees(); 
    
    if (includeInactive) {
      return res.json(rows); // If the user passed includeInactive, all employees are shown
    }
    
    // Creates a 'filtered' list that only saves employees who are currently working 
    const filtered = rows.filter(emp => { // 'emp' is the iterable element in rows
      if (weekStart && weekEnd) { // Logic for Calendar view
        // An employee isStarted if there is no startDate or it is before (or the same as) the weekEnd
        const isStarted = !emp.startDate || emp.startDate <= weekEnd; 
        // An employee isEnded if there is an endDate and it is before the weekStart
        const isEnded = emp.endDate && emp.endDate < weekStart; 
        return isStarted && !isEnded; 
      } else { // Logic for EmployeeManager view
        let today = format(new Date(), 'yyyy-MM-dd'); // If weekStart or weekEnd weren't given, it defaults to today 
        const isStarted = !emp.startDate || emp.startDate <= today;
        const isEnded = emp.endDate && emp.endDate < today;
        return isStarted && !isEnded;
      }
    });

    res.json(filtered); // Sends the filtered list to Vue in JSON format
  } catch (err) {
    console.error("Error in api/employees - getEmployees", err);
    return res.status(500).json({ error: "Internal server error." });
  }
});

/**
 * Create a new employee and assign an ID to it.
 */
app.post('/api/employees', async (req, res) => { 
  const { name, startDate, endDate } = req.body; // Extract data from payload (JSON body)
  
  if (!isValidDate(startDate) || !isValidDate(endDate)) {
    return res.status(400).json({ error: 'Invalid date.' });
  }
  if (!name || !name.trim()) {
    return res.status(400).json({ error: 'Name is required' }); // Removes blanks and spaces with .trim() --> no blank names
  }

  try {
    const newId = await dbHelper.createEmployee(name.trim(), startDate, endDate);
    res.json({ id: newId, name: name.trim(), startDate, endDate }); // Sends the data back to Vue adding the new ID generated by dbHelper.createEmployee()
  } catch (err) {
    console.error("Error in api/employees - createEmployee", err);
    if (err.message && err.message.includes('duplicate value')) {
      return res.status(400).json({ error: "Employee already exists." });
    }
    return res.status(500).json({ error: "Internal server error." });  
  }
});

/**
 * Update an existing employee.
 */
app.put('/api/employees/:id', async (req, res) => { // Handles /api/employees/XX
  const { name, startDate, endDate } = req.body; 
  
  if (!isValidDate(startDate) || !isValidDate(endDate)) {
    return res.status(400).json({ error: 'Invalid date.' });
  }
  if (!name || !name.trim()) {
    return res.status(400).json({ error: 'Name is required' }); 
  }
  
  const id = req.params.id; // Catches the XX from the URL
  
  try {
    await dbHelper.updateEmployee(name.trim(), startDate, endDate, id);
    res.json({ success: true }); // We don't have any data to send back, just a confirm message
  } catch (err) {
    console.error("Error in api/employees/:id - updateEmployee", err);
    return res.status(500).json({ error: "Internal server error." });  
  }
});

/**
 * Makes an employee inactive, logically 'deleting' them.
 */
app.delete('/api/employees/:id', async (req, res) => {
  const id = req.params.id;

  try {
    await dbHelper.deleteEmployee(id);
    res.json({ success: true }); 
  } catch (err) {
    console.error("Error in api/employees/:id - deleteEmployee", err);
    return res.status(500).json({ error: "Internal server error." });  
  }
});

/**
 * Get the schedule for specific dates (list of dates like start to end of a week).
 */
app.get('/api/schedule', async (req, res) => {
  const { startDate, endDate } = req.query; // req.query catches data from URL parameters with ?
  
  if (!isValidDate(startDate) || !isValidDate(endDate)) {
    return res.status(400).json({ error: 'Invalid date.' });
  }
  if (!startDate || !endDate) {
    return res.status(400).json({ error: 'Start date and end date are required' });
  }

  try {
    const rows = await dbHelper.getSchedule(startDate, endDate);
    res.json(rows); // rows have id, employee_id, date, status and note
  } catch (err) {
    console.error("Error in api/schedule - getSchedule", err);
    return res.status(500).json({ error: "Internal server error." });
  }
});

/**
 * Update the status for a specific day.
 */
app.post('/api/schedule/day', async (req, res) => {
  const { employee_id, date, status, note } = req.body; 
  
  if (!isValidDate(date)) {
    return res.status(400).json({ error: 'Invalid date.' });
  }
  if (!employee_id || !date || status === undefined) {
    return res.status(400).json({ error: 'Missing parameters' });
  }
  
  if (status !== "" && !statusOptions.includes(status)) { // Checks if the status is in the valid list
    return res.status(400).json({ error: 'Status not valid!'});
  }

  try {
    await dbHelper.updateDay(employee_id, date, status, note);
    res.json({ success: true });
  } catch (err) {
    console.error("Error in api/schedule/day - updateDay", err);
    return res.status(500).json({ error: "Internal server error." }); 
  }
});

/**
 * Update the status for the whole week (bulk update).
 */
app.post('/api/schedule/week', async (req, res) => {
  const { employee_id, dates, status } = req.body;
  
  // 'dates' should be an array of strings (dates)
  if (!employee_id || !dates || status === undefined || !Array.isArray(dates)) {
    return res.status(400).json({ error: 'Missing or invalid parameters' });
  }
  
  if (status !== "" && !statusOptions.includes(status)) {
    return res.status(400).json({ error: 'Status not valid!'});
  }
  
  if (!dates.every(isValidDate)) {
    return res.status(400).json({ error: 'One or more invalid dates.' });
  }

  try {
    await dbHelper.updateWeek(employee_id, dates, status);
    res.json({ success: true });
  } catch(err) {
    console.error("Error in api/schedule/week - updateWeek", err);
    return res.status(500).json({ error: "Internal server error." });  
  }
});

const distPath = path.join(__dirname, '../dist');
if (fs.existsSync(distPath)) {
  app.use(express.static(distPath)); // Serves static files from dist folder (generated by Vue)
  
  // Catch-all: redirects all non-API requests to index.html"
  app.get(/(.*)/, (req, res) => {
    res.sendFile(path.join(distPath, 'index.html'));
  });
} else {
  console.log("Dist folder not found. Development mode activated.");
}

const PORT = process.env.PORT || 3000;

// Waits for the connection promise from db.js, then starts the server
db.initPromise.then(async () => {
  try {
    statusOptions = await dbHelper.getStatusOptions();
    console.log("Status loaded from Salesforce:", statusOptions);
  } catch (err) {
    console.error("Unable to load statuses from Salesforce, using security fallback.", err);
    // Fallback options
    statusOptions = [
      'Office', 'Remote', 'Office/Remote', 'Remote/Office',
      'Office/Leave', 'Leave/Office', 'Leave/Remote', 'Remote/Leave',
      'Office/Vacation', 'Remote/Vacation', 'Vacation', 'Sick Leave', 'Holiday', 'Other'
    ];
  }
  
  app.listen(PORT, () => {
    console.log(`Server running on port ${PORT} and connected to Salesforce!`);
  });
}).catch(err => {
  console.error("Unable to start server, Salesforce connection error.", err);
});